### ISSUE TITLE
Change FixtureDir to `testdata`

### ISSUE THREAD

**Issue by xorcare** [sebdah/goldie#10]
By default, this package uses the directory `FixtureDir = "fixtures"` , but in Go common practice of using the name `testdata` I would like to see that you have in the package by default used the dir name `testdata`

Examples in standard library
https://github.com/golang/go/tree/master/src/cmd/gofmt/testdata
https://github.com/golang/go/tree/master/src/encoding/json/testdata

P. S. For backward compatibility, you need to share version tags for v1.0.0 and v2.0.0 to current users of the library have not received problems.

**Comment by sebdah** [comment]
@gtrevg Thanks for implementing this. It has just now been merged to master with the v2.0.0 release.
