### ISSUE TITLE
.Contains()-type functionality?

### ISSUE THREAD

**Issue by danawoodman** [sebdah/goldie#27]
Would it be possible to have a `.Contains()` method that would check just part of the golden file? I have a golden file where some parts will change (like generic help text from a CLI) and all I really want to check for is "success" or similar. 

I know that means its not really using the golden file but it would make the test less fragile. 

Thoughts?

**Comment by gtrevg** [comment]
@danawoodman  I think maybe the right design would be to add a `WithCompareFn` option that allows you to pass in your own compare function.  The comparison line (https://github.com/sebdah/goldie/blob/v2.2.0/goldie.go#L378) would then call the compare function.  That way, you could override how it does a comparison between the `actualData` and the `expectedData` (which could just do a substring comparison in your case).
