### ISSUE TITLE
Helper for XML

### ISSUE THREAD

**Issue by derekbassett** [sebdah/goldie#29]
Given encoding.json and encoding.xml are both standard packages it would be nice to have the same support for XML as for JSON.
It is a simple addition to provide the helper method, but does break any other Tester API implementations.

**Comment by derekbassett** [comment]
Generated the following PR https://github.com/sebdah/goldie/pull/28

**Comment by sebdah** [comment]
Forgot to close this issue earlier, the functionality has been shipped. Thanks @derekbassett!
