### ISSUE TITLE
Test FAIL when .golden file change in git branch

### ISSUE THREAD

**Issue by muhammadaser** [sebdah/goldie#6]
i have two branchs, both branch have same `.golden` file.
when i switch branch, and test my project. my test FAIL,

thanks,

**Comment by sebdah** [comment]
Could you elaborate a bit more? So you have two branches

*Branch 1*
- Has a test based on `goldie`
- Has a test file e.g. `1.golden`

*Branch 2*
- Has a test based on `goldie`, but with more cases
- Has test files `1.golden` and `2.golden`

Switching from branch 1 -> 2 is that causing an issue for you?

**Comment by muhammadaser** [comment]
Thanks for answer @sebdah , sorry my english is bad.

_Branch1_ and _Branch2_ have same file, same content.

- **This is my goldie file**

![capture1](https://user-images.githubusercontent.com/3253478/40523877-e695b320-6001-11e8-9f4d-c2121a57d306.PNG)

- **When i test on current branch it is pass,**

![capture2](https://user-images.githubusercontent.com/3253478/40523972-3428a8a4-6002-11e8-982c-5960e1db5720.PNG)

- **Then i checkout to branch master,**

![capture3](https://user-images.githubusercontent.com/3253478/40524097-cccc31ac-6002-11e8-84f2-7948e5634923.PNG)

- **After that, i checkout  to branch rnd agian, and do test,**

![capture4](https://user-images.githubusercontent.com/3253478/40524126-ee653eda-6002-11e8-832b-c67612285335.PNG)

- **Result after doing test**

![capture5](https://user-images.githubusercontent.com/3253478/40524127-eec0f180-6002-11e8-9573-3d361478c00e.PNG)

- **The test fail, same golden file, same content.**

**Comment by sebdah** [comment]
Thank you very much for the detailed write up! Could you please check out `rnd` and then run:

    git diff master path/to/success.golden

And paste the results. I'm thinking this issue is likely related to git / file system.

**Comment by muhammadaser** [comment]
this is the result of 

`git diff master path/to/failure-db-GetTotalBonus-false.golden`.

```
diff --git a/p01/fixtures/testdata/run-program/ngobrol/failure-db-GetTotalBonus-false.golden b/p01/fixtures/testdata/run-program/ngobrol/failure-db-GetTotalBonus-false.golden
new file mode 100644
index 0000000..5306eab
--- /dev/null
+++ b/p01/fixtures/testdata/run-program/ngobrol/failure-db-GetTotalBonus-false.golden
@@ -0,0 +1 @@
+{"code":412,"error":"Cant get total bonus"}
```

**Comment by muhammadaser** [comment]
i will try to merge `rnd` to `master` first, 
after both branch have same file i will try to test again.

**Comment by muhammadaser** [comment]
Ok, its done. when both have same `golden` file its pass.

But when _branch1_ don't have `golden` file, and _branch2_ have `golden` file, and you switch them,
it will fail.

Thanks @sebdah for help me.
