### ISSUE TITLE
Mention inspiration for goldie

### ISSUE THREAD

**Issue by robertzk** [sebdah/goldie#7]
Great package! Maybe it should be mentioned somewhere that the original inspiration for this idea comes from the [Ruby ecosystem](https://github.com/vcr/vcr) (which is where Mitchell took it from).

**Comment by sebdah** [comment]
Thank you! Although I think it's important to acknowledge the shoulder you stand on, I must say I'm not sure about this. I'm not at all aware of that Ruby package, so I don't know if it really qualifies as inspiration?

If you want to formulate something fitting for the readme, I'd be happy to merge it though.

**Comment by robertzk** [comment]
No worries - upon closer inspection, I realized the concept of "golden files" is actually slightly more general than VCR, as it captures comparison against any complex structure -- not just the output of a single network request. I'll close this - thanks for the response!
